### ISSUE TITLE
Synchronous version of all methods

### ISSUE THREAD

**Issue by gyandeeps** [fshost/node-dir#14]
@fshost Is there any plans in future to create a synchronous versions of all the methods?

**Comment by fshost** [comment]
Not at this time as node's built in synchronous versions are themselves pretty straightforward.  The main purpose of this library was to reduce nesting and complexity for using the async versions which require callbacks.  Also, although async, this module does have the option to operate on the results in a sorted order and I'm not sure of the value added for doing the same thing synchronously.  If there is more demand for adding convenience functions or if I've misunderstood your question I might reconsider, especially if a good use case is presented and/or a pull request is submitted (with tests).  For now this library is fulfilling its purpose well in my own projects and I hesitate to add any unnecessary complexity due to scope creep.
